// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveProfileID() {
  return window['go']['main']['App']['ActiveProfileID']();
}

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DefaultLogDirectory() {
  return window['go']['main']['App']['DefaultLogDirectory']();
}

export function DefaultProfile() {
  return window['go']['main']['App']['DefaultProfile']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSkin(arg1) {
  return window['go']['main']['App']['DeleteSkin'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['main']['App']['DeleteTheme'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfigDirectory() {
  return window['go']['main']['App']['GetConfigDirectory']();
}

export function GetControlLines() {
  return window['go']['main']['App']['GetControlLines']();
}

export function GetDefaultConfigDirectory() {
  return window['go']['main']['App']['GetDefaultConfigDirectory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportSkin() {
  return window['go']['main']['App']['ImportSkin']();
}

export function ImportTheme() {
  return window['go']['main']['App']['ImportTheme']();
}

export function ListMissingDrivers() {
  return window['go']['main']['App']['ListMissingDrivers']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSkins() {
  return window['go']['main']['App']['ListSkins']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickConfigDirectory() {
  return window['go']['main']['App']['PickConfigDirectory']();
}

export function PickLogDirectory() {
  return window['go']['main']['App']['PickLogDirectory']();
}

export function PickSendFile() {
  return window['go']['main']['App']['PickSendFile']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SendBreak() {
  return window['go']['main']['App']['SendBreak']();
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}

export function SetConfigDirectory(arg1) {
  return window['go']['main']['App']['SetConfigDirectory'](arg1);
}

export function SetDTR(arg1) {
  return window['go']['main']['App']['SetDTR'](arg1);
}

export function SetRTS(arg1) {
  return window['go']['main']['App']['SetRTS'](arg1);
}

export function SystemTheme() {
  return window['go']['main']['App']['SystemTheme']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
