// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveProfileID() {
  return window['go']['main']['App']['ActiveProfileID']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DefaultProfile() {
  return window['go']['main']['App']['DefaultProfile']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SetDTR(arg1) {
  return window['go']['main']['App']['SetDTR'](arg1);
}

export function SetRTS(arg1) {
  return window['go']['main']['App']['SetRTS'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
