// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {serial} from '../models';

export function ActiveProfileID():Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function CreateProfile(arg1:profiles.Profile):Promise<profiles.Profile>;

export function DefaultProfile():Promise<profiles.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ListPorts():Promise<Array<serial.PortInfo>>;

export function ListProfiles():Promise<Array<profiles.Profile>>;

export function Send(arg1:string):Promise<void>;

export function SetDTR(arg1:boolean):Promise<void>;

export function SetRTS(arg1:boolean):Promise<void>;

export function UpdateProfile(arg1:profiles.Profile):Promise<profiles.Profile>;
