// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {main} from '../models';
import {settings} from '../models';
import {skins} from '../models';
import {themes} from '../models';
import {serial} from '../models';

export function ActiveProfileID():Promise<string>;

export function CancelTransfer():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function CreateProfile(arg1:profiles.Profile):Promise<profiles.Profile>;

export function DefaultLogDirectory():Promise<string>;

export function DefaultProfile():Promise<profiles.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSkin(arg1:string):Promise<void>;

export function DeleteTheme(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfigDirectory():Promise<string>;

export function GetControlLines():Promise<main.ControlLines>;

export function GetDefaultConfigDirectory():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function ImportSkin():Promise<skins.Skin>;

export function ImportTheme():Promise<themes.Theme>;

export function ListMissingDrivers():Promise<Array<serial.USBSerialCandidate>>;

export function ListPorts():Promise<Array<serial.PortInfo>>;

export function ListProfiles():Promise<Array<profiles.Profile>>;

export function ListSkins():Promise<Array<skins.Skin>>;

export function ListThemes():Promise<Array<themes.Theme>>;

export function PickConfigDirectory():Promise<string>;

export function PickLogDirectory():Promise<string>;

export function PickSendFile():Promise<string>;

export function Send(arg1:string):Promise<void>;

export function SendBreak():Promise<void>;

export function SendFile(arg1:string,arg2:string):Promise<void>;

export function SetConfigDirectory(arg1:string):Promise<void>;

export function SetDTR(arg1:boolean):Promise<void>;

export function SetRTS(arg1:boolean):Promise<void>;

export function UpdateProfile(arg1:profiles.Profile):Promise<profiles.Profile>;

export function UpdateSettings(arg1:settings.Settings):Promise<settings.Settings>;
